### ISSUE TITLE
getting error got packets out of order..

### ISSUE THREAD

**Issue by mayur-16** [billcoding/dart_mysql#1]
**am using your package for standalone desktop application with mysql as localhost database.**

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Error 1156 (08S01): Got packets out of order
#0      Handler.checkResponse (package:dart_mysql/src/handlers/handler.dart:77:7)
#1      QueryStreamHandler.processResponse (package:dart_mysql/src/query/query_stream_handler.dart:50:18)
#2      ReqRespConnection._handleData (package:dart_mysql/src/single_connection.dart:349:32)
#3      ReqRespConnection._handleHeader (package:dart_mysql/src/single_connection.dart:318:13)
<asynchronous suspension>
#4      ReqRespConnection._readPacket (package:dart_mysql/src/single_connection.dart:303:7)
<asynchronous suspension>

am getting this error in other flutter packages also like mysql_utils.
 I dont know whether i have to configure anything extra in MySql.

**Comment by billcoding** [comment]
Hi, thanks for submitting this issue.
Can you provide your MySQL Server version, and then i can try.

**Comment by mayur-16** [comment]
> Hi, thanks for submitting this issue. Can you provide your MySQL Server version, and then i can try.

**version 8.0.27(Mysql community server -GPL)**

**Comment by billcoding** [comment]
Hi, pleases sumbit your `Dart` code and `DDL`  sqls.

**Comment by Pencab** [comment]
> **paketinizi localhost veritabanı olarak mysql ile bağımsız masaüstü uygulaması için kullanıyorum.**
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] İşlenmeyen Özel Durum: Hata 1156 (08S01): Paketler bozuk #0 Handler.checkResponse (paket:dart_mysql/src/handlers/handler.dart:77: 7) #1 QueryStreamHandler.processResponse (paket:dart_mysql/src/query/query_stream_handler.dart:50:18) #2 ReqRespConnection._handleData (paket:dart_mysql/src/single_connection.dart:349:32) #3 ReqRespConnection. paket:dart_mysql/src/single_connection.dart:318:13) #4 ReqRespConnection._readPacket (paket:dart_mysql/src/single_connection.dart:303:7)
> 
> mysql_utils gibi diğer çarpıntı paketlerinde de bu hatayı alıyorum. MySql'de ekstra bir şey yapılandırmam gerekip gerekmediğini bilmiyorum.

**Comment by billcoding** [comment]
> > **paketinizi localhost veritabanı olarak mysql ile bağımsız masaüstü uygulaması için kullanıyorum.**
> > [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] İşlenmeyen Özel Durum: Hata 1156 (08S01): Paketler bozuk #0 Handler.checkResponse (paket:dart_mysql/src/handlers/handler.dart:77: 7) #1 QueryStreamHandler.processResponse (paket:dart_mysql/src/query/query_stream_handler.dart:50:18) #2 ReqRespConnection._handleData (paket:dart_mysql/src/single_connection.dart:349:32) #3 ReqRespConnection. paket:dart_mysql/src/single_connection.dart:318:13) #4 ReqRespConnection._readPacket (paket:dart_mysql/src/single_connection.dart:303:7)
> > mysql_utils gibi diğer çarpıntı paketlerinde de bu hatayı alıyorum. MySql'de ekstra bir şey yapılandırmam gerekip gerekmediğini bilmiyorum.

Can you submit your source code?
